version: "3"

services:
    aspnetcore:
        image: "api_gringotts"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - "5000:80"
        networks:
            - gringotts_network


networks:
    gringotts_network:
        driver: "bridge"
